import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { BoxConfig, BaseplateConfig } from '../types/config.js';

const execAsync = promisify(exec);

export class OpenSCADService {
  private scadPath: string;
  private outputPath: string;

  constructor() {
    this.scadPath = path.join(process.cwd(), '..', 'scad', 'gridfinity-extended');
    this.outputPath = path.join(process.cwd(), 'generated');
    
    // Ensure output directory exists
    if (!fs.existsSync(this.outputPath)) {
      fs.mkdirSync(this.outputPath, { recursive: true });
    }
  }

  // Generate Box STL using gridfinity_extended library
  async generateBox(config: BoxConfig): Promise<{ stlUrl: string; scadContent: string; filename: string }> {
    const scadContent = this.generateBoxScad(config);
    return this.renderScad(scadContent, 'box');
  }

  // Generate Baseplate STL using gridfinity_extended library
  async generateBaseplate(config: BaseplateConfig): Promise<{ stlUrl: string; scadContent: string; filename: string }> {
    const scadContent = this.generateBaseplateScad(config);
    return this.renderScad(scadContent, 'baseplate');
  }

  // Generate Box SCAD code using gridfinity_extended library
  generateBoxScad(config: BoxConfig): string {
    // Map lip style
    const lipStyleMap: Record<string, string> = {
      'none': 'none',
      'standard': 'normal',
      'reduced': 'reduced'
    };
    const lipStyle = lipStyleMap[config.lipStyle] || 'normal';

    // Map finger slide
    const fingerSlideType = config.fingerSlide ? 'rounded' : 'none';
    
    // Map finger slide walls [front, back, left, right]
    const fingerSlideWalls: Record<string, string> = {
      'front': '[1,0,0,0]',
      'back': '[0,1,0,0]',
      'left': '[0,0,1,0]',
      'right': '[0,0,0,1]'
    };
    const fingerWalls = config.fingerSlide ? (fingerSlideWalls[config.fingerSlidePosition] || '[1,0,0,0]') : '[0,0,0,0]';

    // Map label walls
    const labelWallsMap: Record<string, string> = {
      'front': '[1,0,0,0]',
      'back': '[0,1,0,0]',
      'left': '[0,0,1,0]',
      'right': '[0,0,0,1]'
    };
    const labelWalls = config.labelEnabled ? (labelWallsMap[config.labelPosition] || '[0,1,0,0]') : '[0,0,0,0]';

    // Efficient floor mapping
    const efficientFloorMap: Record<string, string> = {
      'standard': 'off',
      'efficient': 'on',
      'filled': 'off'
    };
    const efficientFloor = efficientFloorMap[config.baseStyle] || 'off';
    const filledIn = config.baseStyle === 'filled' ? 'enabled' : 'disabled';

    return `// Gridfinity Box - Generated by Gridfinity Generator
// Using ostat/gridfinity_extended_openscad library

include <modules/gridfinity_constants.scad>
use <modules/module_gridfinity_cup.scad>
use <modules/module_gridfinity_block.scad>

/* [Generated Settings] */
width = [${config.width}, 0];
depth = [${config.depth}, 0];
height = [${config.height}, 0];
filled_in = "${filledIn}";
wall_thickness = ${config.wallThickness};

/* [Lip] */
lip_style = "${lipStyle}";

/* [Subdivisions] */
vertical_chambers = ${config.dividersX + 1};
horizontal_chambers = ${config.dividersY + 1};

/* [Base] */
enable_magnets = ${config.magnetEnabled};
enable_screws = ${config.screwEnabled};
magnet_size = [${config.magnetDiameter}, ${config.magnetDepth}];
screw_size = [${config.screwDiameter}, 6];
floor_thickness = ${config.floorThickness};
efficient_floor = "${efficientFloor}";

/* [Label] */
label_style = "${config.labelEnabled ? 'normal' : 'disabled'}";
label_walls = ${labelWalls};
label_size = [0, 14 * ${config.labelWidth / 100}, 0, 0.6];

/* [Finger Slide] */
fingerslide = "${fingerSlideType}";
fingerslide_walls = ${fingerWalls};

/* [Model detail] */
$fa = 8;
$fs = 0.4;

set_environment(
  width = width,
  depth = depth,
  height = height,
  lip_enabled = lip_style != "none",
  render_position = "center",
  help = "disabled")
gridfinity_cup(
  filled_in = filled_in,
  wall_thickness = wall_thickness,
  label_settings = LabelSettings(
    labelStyle = label_style,
    labelPosition = "left",
    labelSize = label_size,
    labelWalls = label_walls),
  finger_slide_settings = FingerSlideSettings(
    type = fingerslide,
    walls = fingerslide_walls),
  cupBase_settings = CupBaseSettings(
    magnetSize = enable_magnets ? magnet_size : [0,0],
    screwSize = enable_screws ? screw_size : [0,0],
    floorThickness = floor_thickness,
    efficientFloor = efficient_floor),
  vertical_chambers = ChamberSettings(chambers_count = vertical_chambers),
  horizontal_chambers = ChamberSettings(chambers_count = horizontal_chambers),
  lip_settings = LipSettings(lipStyle = lip_style));
`;
  }

  // Generate Baseplate SCAD code using gridfinity_extended library
  generateBaseplateScad(config: BaseplateConfig): string {
    // Map style to magnet/screw settings
    const enableMagnets = config.style === 'magnet';
    const enableScrews = config.style === 'screw';
    const weighted = config.style === 'weighted';

    return `// Gridfinity Baseplate - Generated by Gridfinity Generator
// Using ostat/gridfinity_extended_openscad library

include <modules/gridfinity_constants.scad>
use <modules/module_gridfinity_baseplate.scad>

/* [Generated Settings] */
width = ${config.width};
depth = ${config.depth};

/* [Base] */
enable_magnets = ${enableMagnets};
enable_screws = ${enableScrews};
magnet_size = [${config.magnetDiameter}, ${config.magnetDepth}];
screw_size = [${config.screwDiameter}, 6];
weighted = ${weighted};

/* [Model detail] */
$fa = 8;
$fs = 0.4;

gridfinity_baseplate(
  width = width,
  depth = depth,
  magnetSize = enable_magnets ? magnet_size : [0,0],
  screwSize = enable_screws ? screw_size : [0,0],
  weighted = weighted,
  cornerRadius = ${config.cornerRadius});
`;
  }

  // Render SCAD to STL
  private async renderScad(scadContent: string, prefix: string): Promise<{ stlUrl: string; scadContent: string; filename: string }> {
    const id = uuidv4().substring(0, 8);
    const scadFilename = `${prefix}_${id}.scad`;
    const stlFilename = `${prefix}_${id}.stl`;
    const scadFilePath = path.join(this.outputPath, scadFilename);
    const stlFilePath = path.join(this.outputPath, stlFilename);

    // Write SCAD file
    fs.writeFileSync(scadFilePath, scadContent);

    try {
      // Run OpenSCAD to generate STL
      // Use the gridfinity-extended directory as the library path
      const openscadCmd = process.env.OPENSCAD_PATH || 'openscad';
      const cmd = `${openscadCmd} -o "${stlFilePath}" "${scadFilePath}"`;
      
      await execAsync(cmd, { 
        timeout: 120000, // 2 minute timeout
        cwd: this.scadPath // Run from gridfinity-extended directory so includes work
      });

      // Clean up SCAD file
      fs.unlinkSync(scadFilePath);

      return {
        stlUrl: `/files/${stlFilename}`,
        scadContent,
        filename: stlFilename
      };
    } catch (error) {
      // Clean up on error
      if (fs.existsSync(scadFilePath)) {
        fs.unlinkSync(scadFilePath);
      }
      throw error;
    }
  }

  // Clean up old generated files (call periodically)
  cleanupOldFiles(maxAgeMs: number = 3600000): void {
    const now = Date.now();
    const files = fs.readdirSync(this.outputPath);

    for (const file of files) {
      const filePath = path.join(this.outputPath, file);
      const stats = fs.statSync(filePath);
      
      if (now - stats.mtimeMs > maxAgeMs) {
        fs.unlinkSync(filePath);
      }
    }
  }
}
